### ISSUE TITLE
A question about your DataLoader for ImageNet-C

### ISSUE THREAD

**Issue by e0jun** [dhanajitb/petal#1]
Hello
Thank you for your good work.

I have a question about your DataLoader for ImageNet-C.
When implementing PETAL for ImageNet-C, I found that your loader returns only 5,000 samples for each corruption, not all 50,000 samples.

In your configuration file, you specify # of examples for simulating test streams. However, the dataloader only serves the specified samples of the RobustBench library (robustbench/data/imagenet_test_image.ids.txt). 

Is it intended? 
I appreciate any help you can provide.

**Comment by dhanajitb** [comment]
Thanks for pointing out this.
We have only used 5,000 samples, following CoTTA.
The official CoTTA implementation updated this. (refer to their commit here: https://github.com/qinenergy/cotta/commit/4f6957155a560e7c4c115a3a744488235e09a72b)
We have also updated this in our codebase.
